import React from 'react';
import { RecruiterProfile, MicroChallenge, AnonymizedCandidate } from '../../types';
import { GlassCard } from '../../components/GlassCard';
import { DemoBadge } from '../../components/DemoBadge';
import { 
  Briefcase, 
  UserCheck, 
  Users, 
  Layers, 
  Sparkles, 
  ArrowUpRight, 
  ShieldCheck, 
  Building2, 
  MapPin, 
  CheckCircle2, 
  Clock, 
  AlertCircle,
  TrendingUp,
  PlusCircle
} from 'lucide-react';

interface RecruiterDashboardProps {
  recruiter: RecruiterProfile;
  challenges: MicroChallenge[];
  candidates: AnonymizedCandidate[];
  onNavigateTab: (tab: string) => void;
  onSelectCandidate: (candidate: AnonymizedCandidate) => void;
}

export const RecruiterDashboard: React.FC<RecruiterDashboardProps> = ({
  recruiter,
  challenges,
  candidates,
  onNavigateTab,
  onSelectCandidate
}) => {
  const weatherChallenge = challenges.find(c => c.title.includes('Weather')) || challenges[0];

  return (
    <div className="space-y-8 animate-in fade-in duration-300">
      
      {/* Top Banner Notice */}
      <div className="rounded-2xl bg-gradient-to-r from-indigo-950/40 via-slate-900 to-amber-950/40 border border-indigo-500/30 p-4 sm:p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-start sm:items-center gap-3">
          <div className="p-2 rounded-xl bg-indigo-500/20 text-indigo-300 shrink-0">
            <Briefcase size={20} />
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-bold text-white text-sm">Demonstration Recruiter Workspace</span>
              <DemoBadge label="Demo Recruiter" variant="amber" size="sm" />
            </div>
            <p className="text-xs text-slate-300 mt-0.5">
              Logged in as <strong>{recruiter.name}</strong>, {recruiter.role} at <strong>{recruiter.company}</strong>. All talent evaluation matches are generated by demonstration algorithms.
            </p>
          </div>
        </div>
        
        <button
          onClick={() => onNavigateTab('candidate-matching')}
          className="px-4 py-2 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white text-xs font-semibold shadow-lg shadow-indigo-500/20 flex items-center gap-2 shrink-0 transition-all"
        >
          <UserCheck size={14} />
          <span>Review Anonymized Candidates</span>
        </button>
      </div>

      {/* Recruiter Profile Header */}
      <GlassCard glow="indigo" className="p-6 sm:p-8">
        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-5">
            <img
              src={recruiter.avatarUrl}
              alt={recruiter.name}
              className="w-20 h-20 sm:w-24 sm:h-24 rounded-2xl object-cover border-2 border-indigo-500/40 shadow-xl shadow-indigo-500/10"
            />
            <div className="space-y-1.5">
              <div className="flex items-center gap-2.5 flex-wrap">
                <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
                  {recruiter.name}
                </h1>
                <DemoBadge label="Demo Recruiter" variant="indigo" size="sm" />
              </div>

              <p className="text-sm text-indigo-300 font-medium">
                {recruiter.role} • <strong className="text-white">{recruiter.company}</strong>
              </p>

              <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-slate-400 pt-1">
                <span className="flex items-center gap-1.5">
                  <Building2 size={13} className="text-slate-400" />
                  {recruiter.company} (Bengaluru Office)
                </span>
                <span className="flex items-center gap-1.5">
                  <MapPin size={13} className="text-slate-400" />
                  {recruiter.location}
                </span>
                <span className="flex items-center gap-1.5 text-emerald-400 font-mono">
                  <ShieldCheck size={13} /> Verified Employer Partner
                </span>
              </div>
            </div>
          </div>

          {/* Quick Metrics */}
          <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-2 gap-3 w-full lg:w-auto">
            <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800">
              <div className="text-[11px] text-slate-400 font-mono">Active Challenge</div>
              <div className="text-xl font-extrabold text-white mt-0.5">{challenges.length}</div>
              <div className="text-[10px] text-indigo-400">Micro-Challenges Live</div>
            </div>
            <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800">
              <div className="text-[11px] text-slate-400 font-mono">Candidate Pool</div>
              <div className="text-xl font-extrabold text-white mt-0.5">{candidates.length}</div>
              <div className="text-[10px] text-cyan-400">Anonymized Pre-vetted</div>
            </div>
            <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800">
              <div className="text-[11px] text-slate-400 font-mono">Total Submissions</div>
              <div className="text-xl font-extrabold text-white mt-0.5">92</div>
              <div className="text-[10px] text-emerald-400">Verified Evidence Packs</div>
            </div>
            <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800">
              <div className="text-[11px] text-slate-400 font-mono">Avg Match Rate</div>
              <div className="text-xl font-extrabold text-indigo-300 mt-0.5">87.2%</div>
              <div className="text-[10px] text-slate-500">Demonstration Index</div>
            </div>
          </div>
        </div>
      </GlassCard>

      {/* Featured Challenge & Top Matches Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Col: Anonymized Candidates Pipeline */}
        <div className="lg:col-span-7 space-y-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-lg font-bold text-white flex items-center gap-2">
                <UserCheck size={20} className="text-cyan-400" />
                Top Anonymized Matches for "{weatherChallenge.title}"
              </h3>
              <p className="text-xs text-slate-400 mt-0.5">
                Bias-free talent evaluation. Candidate names and personal contacts remain shielded until explicit reveal.
              </p>
            </div>
            <DemoBadge label="Demonstration Matching Algorithm" variant="amber" size="sm" />
          </div>

          <div className="space-y-4">
            {candidates.slice(0, 3).map((cand) => (
              <GlassCard
                key={cand.id}
                hoverEffect
                className="p-5 border-slate-800"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="space-y-2">
                    <div className="flex items-center gap-2.5">
                      <span className="font-mono font-bold text-sm text-cyan-300 bg-slate-900 px-2.5 py-1 rounded-lg border border-slate-800">
                        {cand.maskedId}
                      </span>
                      {cand.isRevealed ? (
                        <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                          REVEALED ({cand.revealedProfile?.name})
                        </span>
                      ) : (
                        <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-800 text-slate-400">
                          SHIELDED CANDIDATE
                        </span>
                      )}
                    </div>

                    {/* Skill indicators */}
                    <div className="flex flex-wrap gap-2 pt-1">
                      {cand.skills.map((s, idx) => (
                        <span
                          key={idx}
                          className="px-2 py-0.5 rounded bg-slate-900 border border-slate-800 text-[11px] text-slate-300"
                        >
                          {s.name}: <strong className="text-cyan-300">{s.score}</strong>
                        </span>
                      ))}
                    </div>

                    <div className="text-xs text-slate-400 pt-1">
                      Evidence Strength: <strong className="text-emerald-400">{cand.evidenceStrength}%</strong> • {cand.topProjects.length} Verified Repositories
                    </div>
                  </div>

                  {/* Match Score & Action */}
                  <div className="text-right flex flex-col items-end gap-2 shrink-0">
                    <div className="p-2 rounded-xl bg-slate-900 border border-slate-800 text-center min-w-[85px]">
                      <div className="text-[10px] font-mono text-slate-400 uppercase">Match</div>
                      <div className="text-xl font-extrabold text-cyan-400 font-mono">
                        {cand.challengeMatch}%
                      </div>
                    </div>

                    <button
                      onClick={() => {
                        onSelectCandidate(cand);
                      }}
                      className="px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold flex items-center gap-1.5 transition-all shadow-md shadow-indigo-600/20"
                    >
                      <span>{cand.isRevealed ? 'View Profile' : 'Inspect Match'}</span>
                      <ArrowUpRight size={13} />
                    </button>
                  </div>
                </div>
              </GlassCard>
            ))}
          </div>

          <div className="text-center pt-2">
            <button
              onClick={() => onNavigateTab('candidate-matching')}
              className="text-xs font-semibold text-cyan-400 hover:text-cyan-300 transition-colors flex items-center gap-1.5 mx-auto"
            >
              <span>View Full Candidate Roster ({candidates.length} Profiles)</span>
              <ArrowUpRight size={14} />
            </button>
          </div>
        </div>

        {/* Right Col: Active Challenges Management */}
        <div className="lg:col-span-5 space-y-6">
          <GlassCard glow="cyan">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3 mb-4">
              <h3 className="text-base font-bold text-white flex items-center gap-2">
                <Layers size={18} className="text-cyan-400" />
                Featured Active Challenge
              </h3>
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 font-mono">
                {weatherChallenge.duration}
              </span>
            </div>

            <div className="space-y-3">
              <h4 className="text-base font-bold text-cyan-300">
                {weatherChallenge.title}
              </h4>
              <p className="text-xs text-slate-400 leading-relaxed">
                {weatherChallenge.description}
              </p>

              <div className="space-y-1.5 pt-2">
                <div className="text-[11px] font-mono text-slate-400 uppercase">Target Skills:</div>
                <div className="flex flex-wrap gap-1.5">
                  {weatherChallenge.requiredSkills.map((s, idx) => (
                    <span key={idx} className="px-2 py-0.5 rounded bg-slate-900 border border-slate-800 text-[11px] text-slate-300">
                      {s}
                    </span>
                  ))}
                </div>
              </div>

              <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800 mt-4 flex items-center justify-between">
                <div>
                  <div className="text-xs text-slate-400 font-mono">Verified Submissions</div>
                  <div className="text-lg font-bold text-white mt-0.5">{weatherChallenge.submissionsCount} Candidates</div>
                </div>
                <button
                  onClick={() => onNavigateTab('challenge-details')}
                  className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-cyan-300 text-xs font-semibold border border-slate-700 transition-colors"
                >
                  Manage Rubric →
                </button>
              </div>
            </div>
          </GlassCard>

          {/* Quick Post Challenge Action */}
          <div className="p-6 rounded-2xl bg-gradient-to-br from-indigo-950/40 via-slate-900 to-purple-950/40 border border-indigo-500/30 space-y-3">
            <h4 className="text-base font-bold text-white flex items-center gap-2">
              <PlusCircle size={18} className="text-indigo-400" />
              Launch New Micro-Challenge
            </h4>
            <p className="text-xs text-slate-300 leading-relaxed">
              Design a 24-72 hour real-world code scenario. Candidates submit Git evidence verified automatically by AST analysis.
            </p>
            <button
              onClick={() => onNavigateTab('create-challenge')}
              className="w-full py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold transition-all shadow-lg shadow-indigo-600/20"
            >
              Configure Challenge Parameters
            </button>
          </div>
        </div>

      </div>

    </div>
  );
};
